# Generated by Django 5.2 on 2025-09-08 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesupload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.Sc', 'B.Sc'), ('M.Tech', 'M.Tech')], max_length=20)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE')], max_length=10)),
                ('semester', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('notes_file', models.FileField(upload_to='notes/')),
                ('is_approved', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NotesUpload',
        ),
    ]
