# Generated by Django 5.2 on 2025-09-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesupload', '0002_note_delete_notesupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
