# Generated by Django 5.2.5 on 2025-09-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesupload', '0003_note_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='notes/covers/'),
        ),
    ]
