# Generated by Django 5.2.5 on 2025-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesupload', '0004_note_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='course',
            field=models.CharField(max_length=50),
        ),
    ]
